### ISSUE TITLE
Unable to get hostnames

### ISSUE THREAD

**Issue by ZebboKlaufix** [errsole/errsole.js#102]
Whenever I switch to `/#/logs` on the dashboard, I get a toast message: `Cannot read properties of null (reading 'attributes')`
But everything seems to work as expected.
Maybe it's because I'm currently running in WSL?

The settings for errsole are the following:
```javascript
errsole.initialize({
  appName: 'MyApp',
  storage: new ErrsoleSQLite('./logs/logs.sqlite'),
  serverName: 'localhost',
});
```

Errsole even logs this error:
```
TypeError: storageConnection.getHostnames is not a function
    at exports.getHostnames (/api/node_modules/errsole/lib/main/server/controllers/logController.js:176:44)
[...]
```

**Comment by mrrishimeena** [comment]
@ZebboKlaufix The issue is due to the latest features we added in Errsole. We have released the Errsole v2.10.x package, but the storage package, *errsole-sqlite*, will be released in a few hours, which will include feature compatibility. I'll update you here once the new storage package is available.

**Comment by mrrishimeena** [comment]
@venki91

**Comment by ZebboKlaufix** [comment]
fixed in the newest version. Thx!
