### ISSUE TITLE
Any way to integrate it with AdonisJS?

### ISSUE THREAD

**Issue by bdavidxyz** [errsole/errsole.js#116]
Thanks for this tool. The docs mention integration with

- Express
- Fastify
- Hapi
- Koa
- Nest

Any guidance for AdonisJS ? Many thanks

**Comment by mrrishimeena** [comment]
**Errsole works with all Node.js frameworks**, including those where specific frameworks are mentioned for 'Proxy Middleware Configuration.' 

For example, if your Node.js app is running on port 9000, the Errsole dashboard, by default, starts on port 8001 unless otherwise specified during configuration. However, if you want to access the Errsole dashboard on port 9000 as well, you will need to configure 'Proxy Middleware' in this specific case.

Link: https://github.com/errsole/errsole.js/blob/master/docs/web-dashboard-access.md
