### ISSUE TITLE
can not print debug msg use 2.8.4

### ISSUE THREAD

**Issue by badboy-tian** [errsole/errsole.js#78]
```
export function logInfo(...msg) {
    const localTime = moment();
    const beijingTime = localTime.clone().tz('Asia/Shanghai');
    const memont = beijingTime.format("HH:mm:ss");
    for (let i = 0; i < msg.length; i++) {
        logger.log("debug", memont + " -> " + (typeof msg[i] === "object" ? CircularJSON.stringify(msg[i]) : msg[i]));
        errsole.debug(msg[i]);
    }
}
```
use logInfo("xxx"), the http://localhost:1337/errsole#/logs not show xxx.  downgrade to 2.8.3, work normal

**Comment by mrrishimeena** [comment]
> ```
> export function logInfo(...msg) {
>     const localTime = moment();
>     const beijingTime = localTime.clone().tz('Asia/Shanghai');
>     const memont = beijingTime.format("HH:mm:ss");
>     for (let i = 0; i < msg.length; i++) {
>         logger.log("debug", memont + " -> " + (typeof msg[i] === "object" ? CircularJSON.stringify(msg[i]) : msg[i]));
>         errsole.debug(msg[i]);
>     }
> }
> ```
> 
> use logInfo("xxx"), the http://localhost:1337/errsole#/logs not show xxx. downgrade to 2.8.3, work normal

When attempting to insert circular or very large objects, a database error can occur due to the limited size of logs we store.

We are working on solutions to store large objects more efficiently, potentially by storing them up to a certain depth level rather than in their entirety if they are too large.

Can you confirm that the problem you are facing isn't related to large objects? I am attaching some screenshots where we tested **errsole.debug** with **errsole@2.84**.

**Screenshot 1:** 

<img width="515" alt="Screenshot 2024-07-03 at 10 57 20 AM" src="https://github.com/errsole/errsole.js/assets/1720744/d4dda31d-3cdd-42da-8777-b3c83f879b92">

**Screenshot 2:**

<img width="640" alt="Screenshot 2024-07-03 at 11 26 47 AM" src="https://github.com/errsole/errsole.js/assets/1720744/9628772a-f24c-481a-ab65-35dca0d9c333">

**Comment by mrrishimeena** [comment]
We found the bug and fixed it in latest release. Please install the latest release of errsole-sqlite [v1.0.2]
`npm install errsole-sqlite@latest`

**Comment by badboy-tian** [comment]
fixed
